// E7: independent JS implementation of frozen adaptive Python benchmark.
// Deterministic synthetic worlds only. E5 audit is read-only, NOT training data.
import {PROFILES, WEIGHTS, SAMPLES, sampleFeatures} from './coherence-model.mjs';
import {buildGearReport} from './gears-model.mjs';

export const ADAPTIVE_SCHEMA='phimirrorhex.e7.adaptive-coherence.v1';
export const TRAIN_SEED=201;
export const VALIDATION_SEED=202;
export const TEST_SEED=203;
export const LEARNING_RATE=2;
export const CHECKPOINTS=Object.freeze([0,16,32,64,96,128]);
export const SHUFFLE_OFFSET=47;

const dot=(a,b)=>a.reduce((sum,w,i)=>sum+w*b[i],0);
const rows=(world,seed)=>{
  if(!PROFILES.includes(world))throw new RangeError('invalid synthetic world');
  return Array.from({length:SAMPLES},(_,i)=>{
    const {features,noise}=sampleFeatures(seed,i);
    return [features,dot(WEIGHTS[world],features)+noise];
  });
};
const stepWeights=(weights,features,label)=>{
  const prediction=dot(weights,features);
  const error=2*(prediction-label);
  const raw=weights.map((weight,i)=>weight*Math.exp(-LEARNING_RATE*error*features[i]));
  const total=raw.reduce((sum,x)=>sum+x,0);
  if(!(total>0))throw new RangeError('adaptive normalization failed');
  return raw.map(v=>v/total);
};
const errors=(weights,samples)=>{
  const values=samples.map(([x,y])=>dot(weights,x)-y);
  const mae=values.reduce((sum,e)=>sum+Math.abs(e),0)/values.length;
  const mse=values.reduce((sum,e)=>sum+e*e,0)/values.length;
  return {mae,mse};
};

export function trainAdaptive(world,initial,{shuffled=false}={}){
  if(!PROFILES.includes(world)||!PROFILES.includes(initial))throw new RangeError('invalid world or initialization');
  if(typeof shuffled!=='boolean')throw new TypeError('shuffled must be boolean');
  const data=rows(world,TRAIN_SEED);
  const labels=data.map(row=>row[1]);
  let weights=[...WEIGHTS[initial]];
  const snapshots=[weights.slice()];
  data.forEach(([features,label],i)=>{
    const target=shuffled?labels[(i+SHUFFLE_OFFSET)%labels.length]:label;
    weights=stepWeights(weights,features,target);
    if(CHECKPOINTS.slice(1).includes(i+1))snapshots.push(weights.slice());
  });
  return {
    final_weights:weights,
    snapshots:snapshots.map((values,i)=>({updates:CHECKPOINTS[i],weights:values})),
    train_updates:SAMPLES,
    train_readings:SAMPLES*6,
    updated_parameters:6,
    gradient_terms:SAMPLES*6,
    exponential_terms:SAMPLES*6,
    feedback_labels_used:SAMPLES,
    source_split:'train_only',
    shuffled_training_labels:shuffled
  };
}

function causalAudit(){
  const r=buildGearReport(.5,.5,true);
  const before=r.history[10],after=r.history[12];
  return {
    source:'phimirrorhex.e5.gear-coupling.v1',
    // Source digest is generated by Python in the portable fixture.
    // Browser model does not misrepresent an unhashed value as its checksum.
    epistemic_origin:'SIMULATED',
    read_only:true,
    fed_to_learner:false,
    step_10:{outer_hidden_difference:before.outer_hidden_distance,coarse_gap:before.outer_gap},
    step_12:{outer_hidden_difference:after.outer_hidden_distance,coarse_gap:after.outer_gap},
    interpretation:'toy hidden difference precedes coarse visibility; not a learned causal discovery'
  };
}

export function adaptiveBenchmark(){
  const worlds=PROFILES.map(world=>{
    const validation=rows(world,VALIDATION_SEED),holdout=rows(world,TEST_SEED);
    const models=Object.fromEntries(PROFILES.map(initial=>{
      const t=trainAdaptive(world,initial);
      return [initial,{
        ...t,
        validation:errors(t.final_weights,validation),
        held_out:errors(t.final_weights,holdout),
        fixed_initial_held_out:errors(WEIGHTS[initial],holdout)
      }];
    }));
    const selected=[...PROFILES].sort((a,b)=>
      models[a].validation.mae-models[b].validation.mae||a.localeCompare(b)
    )[0];
    const scrambled=trainAdaptive(world,selected,{shuffled:true});
    const selectedHoldout=holdout[0];
    return {
      world,
      engineered_target:true,
      selected_on_validation:selected,
      models,
      matched_label_shuffle_control:{
        initialization:selected,trained:scrambled,
        held_out:errors(scrambled.final_weights,holdout),
        same_update_count:SAMPLES,label_offset:SHUFFLE_OFFSET,
        selection_not_retuned:true
      },
      held_out_example:{
        inputs:[...selectedHoldout[0]],target:selectedHoldout[1],
        selected_prediction:dot(models[selected].final_weights,selectedHoldout[0]),
        fixed_equal_prediction:dot(WEIGHTS.equal,selectedHoldout[0])
      }
    };
  });
  return {
    schema:ADAPTIVE_SCHEMA,
    status:'DETERMINISTIC_SYNTHETIC_METHOD_BENCHMARK',
    epistemic_origin:'SIMULATED',
    ground_truth_engineered:true,
    physical_measurement:false,
    consciousness_measured:false,
    action_authorized:false,
    phi_optimality_demonstrated:false,
    training_and_test_isolated:true,
    protocol:{
      seed_train:TRAIN_SEED,
      seed_validation:VALIDATION_SEED,
      seed_test:TEST_SEED,
      cases_per_split:SAMPLES,
      features:6,
      learning_rate:LEARNING_RATE,
      rule:'positive-simplex exponentiated gradient, one online pass',
      objective:'squared-error online gradient; evaluate MAE and MSE',
      updates_per_adaptive_arm:SAMPLES,
      cost_comparison:'adaptive initializations share 6 parameters, 6 readings, 6 gradient/exponential terms per train case',
      fixed_profiles:'untrained descriptive controls, not claimed compute-matched to training',
      candidate_selection:'lowest validation MAE; lexicographic tie break',
      holdout:'never used for fitting, model selection or hyperparameter choice',
      negative_control:'same learning rule with training labels circularly shifted by 47',
      causal_audit:'independent E5 witness, explicitly not an adaptive-training feature',
      learning_rate_is_frozen:true
    },
    profiles:[...PROFILES],worlds,causal_audit:causalAudit()
  };
}
